require:
  - rubocop-rails

Style/FrozenStringLiteralComment:
  Exclude:
    - 'test/test_helper.rb'
    - 'test/application_system_test_case.rb'
    - 'db/seeds.rb'
    - 'config/spring.rb'
    - 'config/routes.rb'
    - 'config/initializers/wrap_parameters.rb'
    - 'config/initializers/permissions_policy.rb'
    - 'config/initializers/mime_types.rb'
    - 'config/initializers/inflections.rb'
    - 'config/initializers/filter_parameter_logging.rb'
    - 'config/initializers/cookies_serializer.rb'
    - 'config/initializers/content_security_policy.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/initializers/assets.rb'
    - 'config/initializers/application_controller_renderer.rb'
    - 'config/environment.rb'
    - 'config/boot.rb'
    - 'config.ru'
    - 'app/models/application_record.rb'
    - 'config/application.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/jobs/application_job.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/controllers/application_controller.rb'
    - 'Rakefile'
    - 'Gemfile'

Rails/RenderInline:
  Exclude:
    - 'test/**/*'

Style/Documentation:
  Exclude:
    - 'app/models/application_record.rb'
    - 'config/application.rb'
    - 'test/**/*'
    - 'app/helpers/application_helper.rb'

Layout/SpaceBeforeFirstArg:
  Exclude:
    - 'Gemfile'

Style/SymbolArray:
  EnforcedStyle: brackets

Bundler/OrderedGems:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'config/puma.rb'
    - 'node_modules/**/*'
    - 'config/environments/**/*'
    - 'bin/**/*'
